# ABOUTME: Schema module exports for Pydantic models used across the application
# ABOUTME: Provides centralized access to all request/response validation schemas

from app.schemas.common import (
    BaseSchema,
    TimestampMixin,
    UUIDMixin,
    PaginationParams,
    PaginationResponse,
    APIResponse,
    HealthCheck,
    ErrorDetail,
    ValidationError,
)

from app.schemas.content import (
    ContentBase,
    ContentCreate,
    ContentUpdate,
    ContentInDB,
    ContentResponse,
    ContentSummary,
    ContentWithPrompts,
    ContentProcessingRequest,
    ContentProcessingResponse,
    ContentBatchProcessingRequest,
    ContentBatchProcessingResponse,
    ContentSearchRequest,
    ContentSearchResponse,
    ContentStatistics,
)

from app.schemas.prompt import (
    PromptBase,
    PromptCreate,
    PromptUpdate,
    PromptInDB,
    PromptResponse,
    PromptSummary,
    PromptWithQuality,
    QualityMetricBase,
    QualityMetricCreate,
    QualityMetricUpdate,
    QualityMetricInDB,
    QualityMetricResponse,
    PromptGenerationRequest,
    PromptGenerationResponse,
    PromptBatchUpdate,
    PromptBatchUpdateResponse,
    MochiCardRequest,
    MochiCardResponse,
    MochiBatchSyncRequest,
    MochiBatchSyncResponse,
    PromptSearchRequest,
    PromptSearchResponse,
    PromptStatistics,
    PromptCreateRequest,
    PromptUpdateRequest,
    PromptBatchCreateRequest,
    MochiCardBatchRequest,
)

from app.schemas.claude_workflow import (
    SubagentResult,
    WorkflowMetrics,
    ContentProcessRequest,
    ContentProcessResponse,
    WorkflowStatusRequest,
    WorkflowStatusResponse,
)

__all__ = [
    # Common schemas
    "BaseSchema",
    "TimestampMixin",
    "UUIDMixin",
    "PaginationParams",
    "PaginationResponse",
    "APIResponse",
    "HealthCheck",
    "ErrorDetail",
    "ValidationError",
    # Content schemas
    "ContentBase",
    "ContentCreate",
    "ContentUpdate",
    "ContentInDB",
    "ContentResponse",
    "ContentSummary",
    "ContentWithPrompts",
    "ContentProcessingRequest",
    "ContentProcessingResponse",
    "ContentBatchProcessingRequest",
    "ContentBatchProcessingResponse",
    "ContentSearchRequest",
    "ContentSearchResponse",
    "ContentStatistics",
    # Prompt schemas
    "PromptBase",
    "PromptCreate",
    "PromptUpdate",
    "PromptInDB",
    "PromptResponse",
    "PromptSummary",
    "PromptWithQuality",
    "QualityMetricBase",
    "QualityMetricCreate",
    "QualityMetricUpdate",
    "QualityMetricInDB",
    "QualityMetricResponse",
    "PromptGenerationRequest",
    "PromptGenerationResponse",
    "PromptBatchUpdate",
    "PromptBatchUpdateResponse",
    "MochiCardRequest",
    "MochiCardResponse",
    "MochiBatchSyncRequest",
    "MochiBatchSyncResponse",
    "PromptSearchRequest",
    "PromptSearchResponse",
    "PromptStatistics",
    "PromptCreateRequest",
    "PromptUpdateRequest",
    "PromptBatchCreateRequest",
    "MochiCardBatchRequest",
    # Claude SDK workflow schemas
    "SubagentResult",
    "WorkflowMetrics",
    "ContentProcessRequest",
    "ContentProcessResponse",
    "WorkflowStatusRequest",
    "WorkflowStatusResponse",
]