"""add_prompt_status_and_fix_uuids

Revision ID: 6a90d14519a1
Revises: ef3cc86afc6e
Create Date: 2025-11-13 19:23:43.602867

IMPORTANT: The UUID type changes from NUMERIC() to UUID() are metadata-only
changes for SQLite. SQLite stores UUIDs as TEXT/BLOB, so these alter_column
operations update SQLAlchemy's type tracking without modifying actual column
storage. The real schema change is adding Prompt.status field.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a90d14519a1'
down_revision = 'ef3cc86afc6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        # Add status column with server_default for existing rows
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW', 'SENT_TO_MOCHI', name='promptstatus'), nullable=False, server_default='PENDING'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index('ix_prompt_status', ['status'], unique=False)

    # Remove server_default now that existing rows have values
    # New rows will use Python-side default from model
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW', 'SENT_TO_MOCHI', name='promptstatus'),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('quality_metrics', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('prompt_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('prompt_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.alter_column('prompt_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('quality_metrics', schema=None) as batch_op:
        batch_op.alter_column('prompt_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # Restore server_default before dropping column (for safe rollback)
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW', 'SENT_TO_MOCHI', name='promptstatus'),
               server_default='PENDING',
               existing_nullable=False)

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_status')
        batch_op.alter_column('content_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###